"""Seed data for logistics carriers from real companies."""
CARRIER_SEEDS = [
    # ── Parcel / Express Delivery ──
    {"name": "SF Express", "category": "parcel", "country": "China", "service_area": "Global", "base_rate_per_kg": 8.5, "min_transit_days": 1, "max_transit_days": 7},
    {"name": "DHL Express", "category": "parcel", "country": "Germany", "service_area": "Global", "base_rate_per_kg": 12.0, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "FedEx", "category": "parcel", "country": "United States", "service_area": "Global", "base_rate_per_kg": 10.5, "min_transit_days": 1, "max_transit_days": 6},
    {"name": "UPS", "category": "parcel", "country": "United States", "service_area": "Global", "base_rate_per_kg": 10.0, "min_transit_days": 1, "max_transit_days": 6},
    {"name": "YTO Express", "category": "parcel", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 4.5, "min_transit_days": 2, "max_transit_days": 10},
    {"name": "ZTO Express", "category": "parcel", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 4.0, "min_transit_days": 2, "max_transit_days": 10},
    {"name": "JD Logistics", "category": "parcel", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 5.0, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "4PX Express", "category": "parcel", "country": "China", "service_area": "Global", "base_rate_per_kg": 6.5, "min_transit_days": 3, "max_transit_days": 14},
    {"name": "Hongkong Post", "category": "parcel", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 5.5, "min_transit_days": 3, "max_transit_days": 15},
    {"name": "Morning Express & Logistics", "category": "parcel", "country": "Hong Kong", "service_area": "Asia-Pacific", "base_rate_per_kg": 5.0, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Shipair Express (China) Ltd.", "category": "parcel", "country": "China", "service_area": "Global", "base_rate_per_kg": 7.0, "min_transit_days": 2, "max_transit_days": 8},

    # ── Air Freight Carriers ──
    {"name": "Cathay Pacific Cargo", "category": "air_freight", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 4.5, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Air China Cargo", "category": "air_freight", "country": "China", "service_area": "Global", "base_rate_per_kg": 3.8, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "China Southern Cargo", "category": "air_freight", "country": "China", "service_area": "Global", "base_rate_per_kg": 3.5, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "China Eastern Airlines Cargo", "category": "air_freight", "country": "China", "service_area": "Global", "base_rate_per_kg": 3.6, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "China Cargo Airlines", "category": "air_freight", "country": "China", "service_area": "Global", "base_rate_per_kg": 3.7, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "SF Airlines", "category": "air_freight", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 3.2, "min_transit_days": 1, "max_transit_days": 3},
    {"name": "Suparna Airlines", "category": "air_freight", "country": "China", "service_area": "Global", "base_rate_per_kg": 3.4, "min_transit_days": 2, "max_transit_days": 6},
    {"name": "China Postal Airlines", "category": "air_freight", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 3.0, "min_transit_days": 2, "max_transit_days": 7},
    {"name": "Eva Air Cargo", "category": "air_freight", "country": "Taiwan", "service_area": "Global", "base_rate_per_kg": 4.0, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "China Airlines Cargo", "category": "air_freight", "country": "Taiwan", "service_area": "Global", "base_rate_per_kg": 4.0, "min_transit_days": 1, "max_transit_days": 5},
    {"name": "Cargolux", "category": "air_freight", "country": "Luxembourg", "service_area": "Global", "base_rate_per_kg": 4.8, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Atlas Air", "category": "air_freight", "country": "United States", "service_area": "Global", "base_rate_per_kg": 5.0, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Polar Air Cargo", "category": "air_freight", "country": "United States", "service_area": "Global", "base_rate_per_kg": 4.8, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Qatar Airways Cargo", "category": "air_freight", "country": "Qatar", "service_area": "Global", "base_rate_per_kg": 4.5, "min_transit_days": 1, "max_transit_days": 4},
    {"name": "Turkish Airlines Cargo", "category": "air_freight", "country": "Turkey", "service_area": "Global", "base_rate_per_kg": 4.2, "min_transit_days": 2, "max_transit_days": 5},
    {"name": "Hong Kong Air Cargo", "category": "air_freight", "country": "Hong Kong", "service_area": "Asia-Pacific", "base_rate_per_kg": 3.5, "min_transit_days": 1, "max_transit_days": 3},
    {"name": "Silk Way West Airlines", "category": "air_freight", "country": "Azerbaijan", "service_area": "Global", "base_rate_per_kg": 4.0, "min_transit_days": 2, "max_transit_days": 6},
    {"name": "Astral Aviation", "category": "air_freight", "country": "Kenya", "service_area": "Africa", "base_rate_per_kg": 5.5, "min_transit_days": 2, "max_transit_days": 8},

    # ── Ocean / Container Shipping Lines ──
    {"name": "COSCO Shipping Lines", "category": "ocean", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.15, "min_transit_days": 10, "max_transit_days": 40},
    {"name": "OOCL (Orient Overseas Container Line)", "category": "ocean", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.18, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "Maersk Line", "category": "ocean", "country": "Denmark", "service_area": "Global", "base_rate_per_kg": 0.20, "min_transit_days": 10, "max_transit_days": 40},
    {"name": "MSC (Mediterranean Shipping Company)", "category": "ocean", "country": "Switzerland", "service_area": "Global", "base_rate_per_kg": 0.19, "min_transit_days": 10, "max_transit_days": 40},
    {"name": "CMA CGM", "category": "ocean", "country": "France", "service_area": "Global", "base_rate_per_kg": 0.20, "min_transit_days": 10, "max_transit_days": 40},
    {"name": "Evergreen Marine", "category": "ocean", "country": "Taiwan", "service_area": "Global", "base_rate_per_kg": 0.18, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "Yang Ming Marine Transport", "category": "ocean", "country": "Taiwan", "service_area": "Global", "base_rate_per_kg": 0.18, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "Hapag-Lloyd", "category": "ocean", "country": "Germany", "service_area": "Global", "base_rate_per_kg": 0.21, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "ONE (Ocean Network Express)", "category": "ocean", "country": "Japan", "service_area": "Global", "base_rate_per_kg": 0.19, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "HMM (Hyundai Merchant Marine)", "category": "ocean", "country": "South Korea", "service_area": "Global", "base_rate_per_kg": 0.18, "min_transit_days": 10, "max_transit_days": 35},
    {"name": "ZIM Integrated Shipping", "category": "ocean", "country": "Israel", "service_area": "Global", "base_rate_per_kg": 0.20, "min_transit_days": 12, "max_transit_days": 40},
    {"name": "Wan Hai Lines", "category": "ocean", "country": "Taiwan", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.16, "min_transit_days": 7, "max_transit_days": 20},
    {"name": "SITC Container Lines", "category": "ocean", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.14, "min_transit_days": 5, "max_transit_days": 15},
    {"name": "Sinotrans Container Lines", "category": "ocean", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.15, "min_transit_days": 7, "max_transit_days": 20},
    {"name": "Zhonggu Logistics (ZGL)", "category": "ocean", "country": "China", "service_area": "China Domestic", "base_rate_per_kg": 0.08, "min_transit_days": 2, "max_transit_days": 7},
    {"name": "China United Lines (CULines)", "category": "ocean", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.15, "min_transit_days": 5, "max_transit_days": 18},
    {"name": "Pacific International Lines (PIL)", "category": "ocean", "country": "Singapore", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.17, "min_transit_days": 7, "max_transit_days": 25},
    {"name": "Regional Container Lines (RCL)", "category": "ocean", "country": "Thailand", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.16, "min_transit_days": 5, "max_transit_days": 18},
    {"name": "KMTC (Korea Marine Transport)", "category": "ocean", "country": "South Korea", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.16, "min_transit_days": 5, "max_transit_days": 15},
    {"name": "Ningbo Ocean Shipping", "category": "ocean", "country": "China", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.13, "min_transit_days": 3, "max_transit_days": 10},
    {"name": "Sinokor Merchant Marine", "category": "ocean", "country": "South Korea", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.16, "min_transit_days": 5, "max_transit_days": 18},
    {"name": "TS Lines", "category": "ocean", "country": "Taiwan", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.15, "min_transit_days": 5, "max_transit_days": 15},
    {"name": "APL (American President Lines)", "category": "ocean", "country": "United States", "service_area": "Global", "base_rate_per_kg": 0.20, "min_transit_days": 10, "max_transit_days": 35},

    # ── Freight Forwarders ──
    {"name": "Sinotrans Ltd.", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Kerry Logistics", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "COSCO Shipping Logistics", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "OOCL Logistics", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Kuehne + Nagel", "category": "forwarder", "country": "Switzerland", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "DHL Supply Chain & Global Forwarding", "category": "forwarder", "country": "Germany", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Expeditors", "category": "forwarder", "country": "United States", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "C.H. Robinson", "category": "forwarder", "country": "United States", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "GEODIS", "category": "forwarder", "country": "France", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "DSV Panalpina", "category": "forwarder", "country": "Denmark", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Nippon Express", "category": "forwarder", "country": "Japan", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "CEVA Logistics", "category": "forwarder", "country": "United Kingdom", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Bolloré Logistics", "category": "forwarder", "country": "France", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "CTS International Logistics", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "EV Cargo", "category": "forwarder", "country": "United Kingdom", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "AWOT Global Logistics", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "CIMC Wetrans Logistics", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Honour Lane Shipping", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Bondex Supply Chain Management", "category": "forwarder", "country": "China", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Rhenus Logistics", "category": "forwarder", "country": "Germany", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Rohlig Logistics", "category": "forwarder", "country": "Germany", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Morrison Express", "category": "forwarder", "country": "Taiwan", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Dimerco Express Group", "category": "forwarder", "country": "Taiwan", "service_area": "Asia-Pacific", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 20},
    {"name": "FreightAmigo", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Cargo Services Far East", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "FedEx Logistics", "category": "forwarder", "country": "United States", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "UPS Supply Chain Solutions", "category": "forwarder", "country": "United States", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Maersk Logistics", "category": "forwarder", "country": "Denmark", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Cargo Partner", "category": "forwarder", "country": "Austria", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},

    # ── Hong Kong Specialized Forwarders ──
    {"name": "AEL-Berkman Forwarding (H.K.) Limited", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Blaiklock Compass World Transport (HK) Ltd", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Clear Freight Limited", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Fairmont Shipping Ltd", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Kerry Freight (Hong Kong) Limited", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Kuehne & Nagel Limited", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "JSP Global Forwarding Limited", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
    {"name": "Hong Kong Air Cargo Forwarders Ltd.", "category": "forwarder", "country": "Hong Kong", "service_area": "Global", "base_rate_per_kg": 0.0, "min_transit_days": 1, "max_transit_days": 30},
]
